export const giftCatalog = [
  { coins: 1, name: 'Rose', icon: '🌹' },
  { coins: 2, name: 'Clap Burst', icon: '👏' },
  { coins: 3, name: 'Star Sparkle', icon: '⭐' },
  { coins: 4, name: 'Fire Reaction', icon: '🔥' },
  { coins: 5, name: 'Heart Pop', icon: '💖' },
  { coins: 6, name: 'Mic Boost', icon: '🎤' },
  { coins: 7, name: 'Energy Bolt', icon: '⚡' },
  { coins: 8, name: 'Music Notes', icon: '🎶' },
  { coins: 9, name: 'Mini Crown', icon: '👑' },
  { coins: 10, name: 'Golden Star', icon: '🌟' },
  { coins: 11, name: 'Diamond', icon: '💎' },
  { coins: 12, name: 'Rocket', icon: '🚀' },
  { coins: 13, name: 'Standing Ovation', icon: '🎭' },
  { coins: 14, name: 'Hype Speaker', icon: '🔊' },
  { coins: 15, name: 'Mini Trophy', icon: '🏆' },
  { coins: 16, name: 'Lion', icon: '🦁' },
  { coins: 17, name: 'Rainbow', icon: '🌈' },
  { coins: 18, name: 'Royal Crown', icon: '👑' },
  { coins: 19, name: 'Fireworks', icon: '🎆' },
  { coins: 20, name: 'Golden Spotlight', icon: '⭐🏆' },
];
