const giftCatalog = [
  {
    "id": "love-common-velvet-ember-1",
    "gift_slug": "love-common-velvet-ember-1",
    "name": "Common Velvet Ember",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 125,
    "tier": "Common",
    "category": "Love",
    "description": "A common love token that courses warmth through every courtly admirer.",
    "popularityScore": 52,
    "imageUrl": "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "love-common-aurora-bloom-2",
    "gift_slug": "love-common-aurora-bloom-2",
    "name": "Common Aurora Bloom",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 150,
    "tier": "Common",
    "category": "Love",
    "description": "A common love token that drapes the chat in neon affection.",
    "popularityScore": 55,
    "imageUrl": "https://images.unsplash.com/photo-1514354466706-a82849d4f27a?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "love-rare-aurora-bloom-1",
    "gift_slug": "love-rare-aurora-bloom-1",
    "name": "Rare Aurora Bloom",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 285,
    "tier": "Rare",
    "category": "Love",
    "description": "A rare love token that whispers soft promises across the stream.",
    "popularityScore": 63,
    "imageUrl": "https://images.unsplash.com/photo-1514354466706-a82849d4f27a?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "love-rare-gilded-rose-2",
    "gift_slug": "love-rare-gilded-rose-2",
    "name": "Rare Gilded Rose",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 310,
    "tier": "Rare",
    "category": "Love",
    "description": "A rare love token that floods the stage with gilded adoration.",
    "popularityScore": 66,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "love-epic-gilded-rose-1",
    "gift_slug": "love-epic-gilded-rose-1",
    "name": "Epic Gilded Rose",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 525,
    "tier": "Epic",
    "category": "Love",
    "description": "A epic love token that shines like a golden cupid arrow.",
    "popularityScore": 72,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "love-epic-eternal-wink-2",
    "gift_slug": "love-epic-eternal-wink-2",
    "name": "Epic Eternal Wink",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 550,
    "tier": "Epic",
    "category": "Love",
    "description": "A epic love token that courses warmth through every courtly admirer.",
    "popularityScore": 75,
    "imageUrl": "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "love-legendary-eternal-wink-1",
    "gift_slug": "love-legendary-eternal-wink-1",
    "name": "Legendary Eternal Wink",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1105,
    "tier": "Legendary",
    "category": "Love",
    "description": "A legendary love token that drapes the chat in neon affection.",
    "popularityScore": 83,
    "imageUrl": "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "love-legendary-velvet-ember-2",
    "gift_slug": "love-legendary-velvet-ember-2",
    "name": "Legendary Velvet Ember",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1130,
    "tier": "Legendary",
    "category": "Love",
    "description": "A legendary love token that whispers soft promises across the stream.",
    "popularityScore": 86,
    "imageUrl": "https://images.unsplash.com/photo-1514354466706-a82849d4f27a?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "love-mythic-velvet-ember-1",
    "gift_slug": "love-mythic-velvet-ember-1",
    "name": "Mythic Velvet Ember",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2205,
    "tier": "Mythic",
    "category": "Love",
    "description": "A mythic love token that floods the stage with gilded adoration.",
    "popularityScore": 94,
    "imageUrl": "https://images.unsplash.com/photo-1514354466706-a82849d4f27a?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "love-mythic-aurora-bloom-2",
    "gift_slug": "love-mythic-aurora-bloom-2",
    "name": "Mythic Aurora Bloom",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2230,
    "tier": "Mythic",
    "category": "Love",
    "description": "A mythic love token that shines like a golden cupid arrow.",
    "popularityScore": 97,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "funny-common-jester-spark-1",
    "gift_slug": "funny-common-jester-spark-1",
    "name": "Common Jester Spark",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 116,
    "tier": "Common",
    "category": "Funny",
    "description": "A common funny token that uncorks belly laughs with neon confetti.",
    "popularityScore": 54,
    "imageUrl": "https://images.unsplash.com/photo-1507878866276-a947ef722fee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "funny-common-trickster-pulse-2",
    "gift_slug": "funny-common-trickster-pulse-2",
    "name": "Common Trickster Pulse",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 141,
    "tier": "Common",
    "category": "Funny",
    "description": "A common funny token that drops a prank with a soft gold glow.",
    "popularityScore": 57,
    "imageUrl": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "funny-rare-trickster-pulse-1",
    "gift_slug": "funny-rare-trickster-pulse-1",
    "name": "Rare Trickster Pulse",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 276,
    "tier": "Rare",
    "category": "Funny",
    "description": "A rare funny token that launches a ridiculous burst of charm.",
    "popularityScore": 65,
    "imageUrl": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "funny-rare-banana-slip-2",
    "gift_slug": "funny-rare-banana-slip-2",
    "name": "Rare Banana Slip",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 301,
    "tier": "Rare",
    "category": "Funny",
    "description": "A rare funny token that throws a glittering punchline into the room.",
    "popularityScore": 68,
    "imageUrl": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "funny-epic-banana-slip-1",
    "gift_slug": "funny-epic-banana-slip-1",
    "name": "Epic Banana Slip",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 516,
    "tier": "Epic",
    "category": "Funny",
    "description": "A epic funny token that bounces a playful wink across Troll City.",
    "popularityScore": 74,
    "imageUrl": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "funny-epic-giggle-bomb-2",
    "gift_slug": "funny-epic-giggle-bomb-2",
    "name": "Epic Giggle Bomb",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 541,
    "tier": "Epic",
    "category": "Funny",
    "description": "A epic funny token that uncorks belly laughs with neon confetti.",
    "popularityScore": 77,
    "imageUrl": "https://images.unsplash.com/photo-1507878866276-a947ef722fee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "funny-legendary-giggle-bomb-1",
    "gift_slug": "funny-legendary-giggle-bomb-1",
    "name": "Legendary Giggle Bomb",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1096,
    "tier": "Legendary",
    "category": "Funny",
    "description": "A legendary funny token that drops a prank with a soft gold glow.",
    "popularityScore": 85,
    "imageUrl": "https://images.unsplash.com/photo-1507878866276-a947ef722fee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "funny-legendary-jester-spark-2",
    "gift_slug": "funny-legendary-jester-spark-2",
    "name": "Legendary Jester Spark",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1121,
    "tier": "Legendary",
    "category": "Funny",
    "description": "A legendary funny token that launches a ridiculous burst of charm.",
    "popularityScore": 88,
    "imageUrl": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "funny-mythic-jester-spark-1",
    "gift_slug": "funny-mythic-jester-spark-1",
    "name": "Mythic Jester Spark",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2196,
    "tier": "Mythic",
    "category": "Funny",
    "description": "A mythic funny token that throws a glittering punchline into the room.",
    "popularityScore": 96,
    "imageUrl": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "funny-mythic-trickster-pulse-2",
    "gift_slug": "funny-mythic-trickster-pulse-2",
    "name": "Mythic Trickster Pulse",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2221,
    "tier": "Mythic",
    "category": "Funny",
    "description": "A mythic funny token that bounces a playful wink across Troll City.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "luxury-common-imperial-drape-1",
    "gift_slug": "luxury-common-imperial-drape-1",
    "name": "Common Imperial Drape",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 172,
    "tier": "Common",
    "category": "Luxury",
    "description": "A common luxury token that splashes opulent light across the arena.",
    "popularityScore": 56,
    "imageUrl": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "luxury-common-golden-verve-2",
    "gift_slug": "luxury-common-golden-verve-2",
    "name": "Common Golden Verve",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 197,
    "tier": "Common",
    "category": "Luxury",
    "description": "A common luxury token that weaves a velvet glow for every viewer.",
    "popularityScore": 59,
    "imageUrl": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "luxury-rare-golden-verve-1",
    "gift_slug": "luxury-rare-golden-verve-1",
    "name": "Rare Golden Verve",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 332,
    "tier": "Rare",
    "category": "Luxury",
    "description": "A rare luxury token that pours liquid gold over the experience.",
    "popularityScore": 67,
    "imageUrl": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "luxury-rare-diamond-cascade-2",
    "gift_slug": "luxury-rare-diamond-cascade-2",
    "name": "Rare Diamond Cascade",
    "icon": "?",
    "animationType": "spark",
    "coinCost": 357,
    "tier": "Rare",
    "category": "Luxury",
    "description": "A rare luxury token that elevates the moment with crystal sparks.",
    "popularityScore": 70,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "luxury-epic-diamond-cascade-1",
    "gift_slug": "luxury-epic-diamond-cascade-1",
    "name": "Epic Diamond Cascade",
    "icon": "?",
    "animationType": "burst",
    "coinCost": 572,
    "tier": "Epic",
    "category": "Luxury",
    "description": "A epic luxury token that piques every gaze with gilded flair.",
    "popularityScore": 76,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "luxury-epic-silk-veil-2",
    "gift_slug": "luxury-epic-silk-veil-2",
    "name": "Epic Silk Veil",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 597,
    "tier": "Epic",
    "category": "Luxury",
    "description": "A epic luxury token that splashes opulent light across the arena.",
    "popularityScore": 79,
    "imageUrl": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "luxury-legendary-silk-veil-1",
    "gift_slug": "luxury-legendary-silk-veil-1",
    "name": "Legendary Silk Veil",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1152,
    "tier": "Legendary",
    "category": "Luxury",
    "description": "A legendary luxury token that weaves a velvet glow for every viewer.",
    "popularityScore": 87,
    "imageUrl": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "luxury-legendary-imperial-drape-2",
    "gift_slug": "luxury-legendary-imperial-drape-2",
    "name": "Legendary Imperial Drape",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1177,
    "tier": "Legendary",
    "category": "Luxury",
    "description": "A legendary luxury token that pours liquid gold over the experience.",
    "popularityScore": 90,
    "imageUrl": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "luxury-mythic-imperial-drape-1",
    "gift_slug": "luxury-mythic-imperial-drape-1",
    "name": "Mythic Imperial Drape",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2252,
    "tier": "Mythic",
    "category": "Luxury",
    "description": "A mythic luxury token that elevates the moment with crystal sparks.",
    "popularityScore": 98,
    "imageUrl": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "luxury-mythic-golden-verve-2",
    "gift_slug": "luxury-mythic-golden-verve-2",
    "name": "Mythic Golden Verve",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2277,
    "tier": "Mythic",
    "category": "Luxury",
    "description": "A mythic luxury token that piques every gaze with gilded flair.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "animals-common-draconic-roar-1",
    "gift_slug": "animals-common-draconic-roar-1",
    "name": "Common Draconic Roar",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 138,
    "tier": "Common",
    "category": "Animals",
    "description": "A common animals token that leashes wild neon energy for the court.",
    "popularityScore": 58,
    "imageUrl": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "animals-common-silver-paw-2",
    "gift_slug": "animals-common-silver-paw-2",
    "name": "Common Silver Paw",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 163,
    "tier": "Common",
    "category": "Animals",
    "description": "A common animals token that lets a savage roar shake the canvas.",
    "popularityScore": 61,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "animals-rare-silver-paw-1",
    "gift_slug": "animals-rare-silver-paw-1",
    "name": "Rare Silver Paw",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 298,
    "tier": "Rare",
    "category": "Animals",
    "description": "A rare animals token that lets fangs and fluff dance in golden light.",
    "popularityScore": 69,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "animals-rare-aurora-fang-2",
    "gift_slug": "animals-rare-aurora-fang-2",
    "name": "Rare Aurora Fang",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 323,
    "tier": "Rare",
    "category": "Animals",
    "description": "A rare animals token that prances with regal paws across the feed.",
    "popularityScore": 72,
    "imageUrl": "https://images.unsplash.com/photo-1501706362039-c6e0a14b3c8a?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "animals-epic-aurora-fang-1",
    "gift_slug": "animals-epic-aurora-fang-1",
    "name": "Epic Aurora Fang",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 538,
    "tier": "Epic",
    "category": "Animals",
    "description": "A epic animals token that leaps through the stream with animal grace.",
    "popularityScore": 78,
    "imageUrl": "https://images.unsplash.com/photo-1501706362039-c6e0a14b3c8a?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "animals-epic-mythic-mane-2",
    "gift_slug": "animals-epic-mythic-mane-2",
    "name": "Epic Mythic Mane",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 563,
    "tier": "Epic",
    "category": "Animals",
    "description": "A epic animals token that leashes wild neon energy for the court.",
    "popularityScore": 81,
    "imageUrl": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "animals-legendary-mythic-mane-1",
    "gift_slug": "animals-legendary-mythic-mane-1",
    "name": "Legendary Mythic Mane",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1118,
    "tier": "Legendary",
    "category": "Animals",
    "description": "A legendary animals token that lets a savage roar shake the canvas.",
    "popularityScore": 89,
    "imageUrl": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "animals-legendary-draconic-roar-2",
    "gift_slug": "animals-legendary-draconic-roar-2",
    "name": "Legendary Draconic Roar",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1143,
    "tier": "Legendary",
    "category": "Animals",
    "description": "A legendary animals token that lets fangs and fluff dance in golden light.",
    "popularityScore": 92,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "animals-mythic-draconic-roar-1",
    "gift_slug": "animals-mythic-draconic-roar-1",
    "name": "Mythic Draconic Roar",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2218,
    "tier": "Mythic",
    "category": "Animals",
    "description": "A mythic animals token that prances with regal paws across the feed.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "animals-mythic-silver-paw-2",
    "gift_slug": "animals-mythic-silver-paw-2",
    "name": "Mythic Silver Paw",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2243,
    "tier": "Mythic",
    "category": "Animals",
    "description": "A mythic animals token that leaps through the stream with animal grace.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1501706362039-c6e0a14b3c8a?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "food-common-saffron-feast-1",
    "gift_slug": "food-common-saffron-feast-1",
    "name": "Common Saffron Feast",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 149,
    "tier": "Common",
    "category": "Food",
    "description": "A common food token that drops decadent delight into chat.",
    "popularityScore": 60,
    "imageUrl": "https://images.unsplash.com/photo-1432139555190-58524dae6a55?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "food-common-midnight-truffle-2",
    "gift_slug": "food-common-midnight-truffle-2",
    "name": "Common Midnight Truffle",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 174,
    "tier": "Common",
    "category": "Food",
    "description": "A common food token that pours a feast of neon flavor over the stream.",
    "popularityScore": 63,
    "imageUrl": "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "food-rare-midnight-truffle-1",
    "gift_slug": "food-rare-midnight-truffle-1",
    "name": "Rare Midnight Truffle",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 309,
    "tier": "Rare",
    "category": "Food",
    "description": "A rare food token that toasts with shimmering bubbles of joy.",
    "popularityScore": 71,
    "imageUrl": "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "food-rare-velvet-bite-2",
    "gift_slug": "food-rare-velvet-bite-2",
    "name": "Rare Velvet Bite",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 334,
    "tier": "Rare",
    "category": "Food",
    "description": "A rare food token that serves a dessert of golden sparks.",
    "popularityScore": 74,
    "imageUrl": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "food-epic-velvet-bite-1",
    "gift_slug": "food-epic-velvet-bite-1",
    "name": "Epic Velvet Bite",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 549,
    "tier": "Epic",
    "category": "Food",
    "description": "A epic food token that fills the room with delicious warmth.",
    "popularityScore": 80,
    "imageUrl": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "food-epic-eclipse-sip-2",
    "gift_slug": "food-epic-eclipse-sip-2",
    "name": "Epic Eclipse Sip",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 574,
    "tier": "Epic",
    "category": "Food",
    "description": "A epic food token that drops decadent delight into chat.",
    "popularityScore": 83,
    "imageUrl": "https://images.unsplash.com/photo-1432139555190-58524dae6a55?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "food-legendary-eclipse-sip-1",
    "gift_slug": "food-legendary-eclipse-sip-1",
    "name": "Legendary Eclipse Sip",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1129,
    "tier": "Legendary",
    "category": "Food",
    "description": "A legendary food token that pours a feast of neon flavor over the stream.",
    "popularityScore": 91,
    "imageUrl": "https://images.unsplash.com/photo-1432139555190-58524dae6a55?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "food-legendary-saffron-feast-2",
    "gift_slug": "food-legendary-saffron-feast-2",
    "name": "Legendary Saffron Feast",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1154,
    "tier": "Legendary",
    "category": "Food",
    "description": "A legendary food token that toasts with shimmering bubbles of joy.",
    "popularityScore": 94,
    "imageUrl": "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "food-mythic-saffron-feast-1",
    "gift_slug": "food-mythic-saffron-feast-1",
    "name": "Mythic Saffron Feast",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2229,
    "tier": "Mythic",
    "category": "Food",
    "description": "A mythic food token that serves a dessert of golden sparks.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "food-mythic-midnight-truffle-2",
    "gift_slug": "food-mythic-midnight-truffle-2",
    "name": "Mythic Midnight Truffle",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2254,
    "tier": "Mythic",
    "category": "Food",
    "description": "A mythic food token that fills the room with delicious warmth.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "magic-common-runic-bloom-1",
    "gift_slug": "magic-common-runic-bloom-1",
    "name": "Common Runic Bloom",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 165,
    "tier": "Common",
    "category": "Magic",
    "description": "A common magic token that summons luminous sigils over the moment.",
    "popularityScore": 62,
    "imageUrl": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "magic-common-mystic-pulse-2",
    "gift_slug": "magic-common-mystic-pulse-2",
    "name": "Common Mystic Pulse",
    "icon": "?",
    "animationType": "glow",
    "coinCost": 190,
    "tier": "Common",
    "category": "Magic",
    "description": "A common magic token that sprinkles stardust across every view.",
    "popularityScore": 65,
    "imageUrl": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "magic-rare-mystic-pulse-1",
    "gift_slug": "magic-rare-mystic-pulse-1",
    "name": "Rare Mystic Pulse",
    "icon": "?",
    "animationType": "spark",
    "coinCost": 325,
    "tier": "Rare",
    "category": "Magic",
    "description": "A rare magic token that casts shimmering sparks that flutter.",
    "popularityScore": 73,
    "imageUrl": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "magic-rare-arcane-flutter-2",
    "gift_slug": "magic-rare-arcane-flutter-2",
    "name": "Rare Arcane Flutter",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 350,
    "tier": "Rare",
    "category": "Magic",
    "description": "A rare magic token that merges midnight stars with courtly chants.",
    "popularityScore": 76,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "magic-epic-arcane-flutter-1",
    "gift_slug": "magic-epic-arcane-flutter-1",
    "name": "Epic Arcane Flutter",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 565,
    "tier": "Epic",
    "category": "Magic",
    "description": "A epic magic token that lets spells ride golden ripples through chat.",
    "popularityScore": 82,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "magic-epic-lunar-sigil-2",
    "gift_slug": "magic-epic-lunar-sigil-2",
    "name": "Epic Lunar Sigil",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 590,
    "tier": "Epic",
    "category": "Magic",
    "description": "A epic magic token that summons luminous sigils over the moment.",
    "popularityScore": 85,
    "imageUrl": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "magic-legendary-lunar-sigil-1",
    "gift_slug": "magic-legendary-lunar-sigil-1",
    "name": "Legendary Lunar Sigil",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1145,
    "tier": "Legendary",
    "category": "Magic",
    "description": "A legendary magic token that sprinkles stardust across every view.",
    "popularityScore": 93,
    "imageUrl": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "magic-legendary-runic-bloom-2",
    "gift_slug": "magic-legendary-runic-bloom-2",
    "name": "Legendary Runic Bloom",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1170,
    "tier": "Legendary",
    "category": "Magic",
    "description": "A legendary magic token that casts shimmering sparks that flutter.",
    "popularityScore": 96,
    "imageUrl": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "magic-mythic-runic-bloom-1",
    "gift_slug": "magic-mythic-runic-bloom-1",
    "name": "Mythic Runic Bloom",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2245,
    "tier": "Mythic",
    "category": "Magic",
    "description": "A mythic magic token that merges midnight stars with courtly chants.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "magic-mythic-mystic-pulse-2",
    "gift_slug": "magic-mythic-mystic-pulse-2",
    "name": "Mythic Mystic Pulse",
    "icon": "?",
    "animationType": "wave",
    "coinCost": 2270,
    "tier": "Mythic",
    "category": "Magic",
    "description": "A mythic magic token that lets spells ride golden ripples through chat.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "party-common-neon-toast-1",
    "gift_slug": "party-common-neon-toast-1",
    "name": "Common Neon Toast",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 166,
    "tier": "Common",
    "category": "Party",
    "description": "A common party token that pops a confetti storm of neon delight.",
    "popularityScore": 64,
    "imageUrl": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "party-common-midnight-confetti-2",
    "gift_slug": "party-common-midnight-confetti-2",
    "name": "Common Midnight Confetti",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 191,
    "tier": "Common",
    "category": "Party",
    "description": "A common party token that ignites a toast with shimmering vibes.",
    "popularityScore": 67,
    "imageUrl": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "party-rare-midnight-confetti-1",
    "gift_slug": "party-rare-midnight-confetti-1",
    "name": "Rare Midnight Confetti",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 326,
    "tier": "Rare",
    "category": "Party",
    "description": "A rare party token that spins a gold spark of collective hype.",
    "popularityScore": 75,
    "imageUrl": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "party-rare-gold-spark-2",
    "gift_slug": "party-rare-gold-spark-2",
    "name": "Rare Gold Spark",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 351,
    "tier": "Rare",
    "category": "Party",
    "description": "A rare party token that drops bassy fireworks for every guest.",
    "popularityScore": 78,
    "imageUrl": "https://images.unsplash.com/photo-1518733057094-95bda4b8c1bb?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "party-epic-gold-spark-1",
    "gift_slug": "party-epic-gold-spark-1",
    "name": "Epic Gold Spark",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 566,
    "tier": "Epic",
    "category": "Party",
    "description": "A epic party token that sends a chant of glitter-fueled chaos.",
    "popularityScore": 84,
    "imageUrl": "https://images.unsplash.com/photo-1518733057094-95bda4b8c1bb?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "party-epic-chaos-drop-2",
    "gift_slug": "party-epic-chaos-drop-2",
    "name": "Epic Chaos Drop",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 591,
    "tier": "Epic",
    "category": "Party",
    "description": "A epic party token that pops a confetti storm of neon delight.",
    "popularityScore": 87,
    "imageUrl": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "party-legendary-chaos-drop-1",
    "gift_slug": "party-legendary-chaos-drop-1",
    "name": "Legendary Chaos Drop",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1146,
    "tier": "Legendary",
    "category": "Party",
    "description": "A legendary party token that ignites a toast with shimmering vibes.",
    "popularityScore": 95,
    "imageUrl": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "party-legendary-neon-toast-2",
    "gift_slug": "party-legendary-neon-toast-2",
    "name": "Legendary Neon Toast",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1171,
    "tier": "Legendary",
    "category": "Party",
    "description": "A legendary party token that spins a gold spark of collective hype.",
    "popularityScore": 98,
    "imageUrl": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "party-mythic-neon-toast-1",
    "gift_slug": "party-mythic-neon-toast-1",
    "name": "Mythic Neon Toast",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2246,
    "tier": "Mythic",
    "category": "Party",
    "description": "A mythic party token that drops bassy fireworks for every guest.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "party-mythic-midnight-confetti-2",
    "gift_slug": "party-mythic-midnight-confetti-2",
    "name": "Mythic Midnight Confetti",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2271,
    "tier": "Mythic",
    "category": "Party",
    "description": "A mythic party token that sends a chant of glitter-fueled chaos.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1518733057094-95bda4b8c1bb?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "sports-common-victory-swing-1",
    "gift_slug": "sports-common-victory-swing-1",
    "name": "Common Victory Swing",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 162,
    "tier": "Common",
    "category": "Sports",
    "description": "A common sports token that blasts championship energy into the feed.",
    "popularityScore": 66,
    "imageUrl": "https://images.unsplash.com/photo-1502720705749-3c6f3f8c2c2c?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "sports-common-gold-roster-2",
    "gift_slug": "sports-common-gold-roster-2",
    "name": "Common Gold Roster",
    "icon": "?",
    "animationType": "glow",
    "coinCost": 187,
    "tier": "Common",
    "category": "Sports",
    "description": "A common sports token that crosses the finish line with neon glory.",
    "popularityScore": 69,
    "imageUrl": "https://images.unsplash.com/photo-1502720705749-3c6f3f8c2c2c?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "sports-rare-gold-roster-1",
    "gift_slug": "sports-rare-gold-roster-1",
    "name": "Rare Gold Roster",
    "icon": "?",
    "animationType": "spark",
    "coinCost": 322,
    "tier": "Rare",
    "category": "Sports",
    "description": "A rare sports token that serves a flashy dunk of gold.",
    "popularityScore": 77,
    "imageUrl": "https://images.unsplash.com/photo-1502720705749-3c6f3f8c2c2c?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "sports-rare-streak-burst-2",
    "gift_slug": "sports-rare-streak-burst-2",
    "name": "Rare Streak Burst",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 347,
    "tier": "Rare",
    "category": "Sports",
    "description": "A rare sports token that scores a spotlight that streaks through chat.",
    "popularityScore": 80,
    "imageUrl": "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "sports-epic-streak-burst-1",
    "gift_slug": "sports-epic-streak-burst-1",
    "name": "Epic Streak Burst",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 562,
    "tier": "Epic",
    "category": "Sports",
    "description": "A epic sports token that celebrates with a roaring victory pulse.",
    "popularityScore": 86,
    "imageUrl": "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "sports-epic-podium-flash-2",
    "gift_slug": "sports-epic-podium-flash-2",
    "name": "Epic Podium Flash",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 587,
    "tier": "Epic",
    "category": "Sports",
    "description": "A epic sports token that blasts championship energy into the feed.",
    "popularityScore": 89,
    "imageUrl": "https://images.unsplash.com/photo-1502720705749-3c6f3f8c2c2c?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "sports-legendary-podium-flash-1",
    "gift_slug": "sports-legendary-podium-flash-1",
    "name": "Legendary Podium Flash",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1142,
    "tier": "Legendary",
    "category": "Sports",
    "description": "A legendary sports token that crosses the finish line with neon glory.",
    "popularityScore": 97,
    "imageUrl": "https://images.unsplash.com/photo-1502720705749-3c6f3f8c2c2c?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "sports-legendary-victory-swing-2",
    "gift_slug": "sports-legendary-victory-swing-2",
    "name": "Legendary Victory Swing",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1167,
    "tier": "Legendary",
    "category": "Sports",
    "description": "A legendary sports token that serves a flashy dunk of gold.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1502720705749-3c6f3f8c2c2c?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "sports-mythic-victory-swing-1",
    "gift_slug": "sports-mythic-victory-swing-1",
    "name": "Mythic Victory Swing",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2242,
    "tier": "Mythic",
    "category": "Sports",
    "description": "A mythic sports token that scores a spotlight that streaks through chat.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1502720705749-3c6f3f8c2c2c?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "sports-mythic-gold-roster-2",
    "gift_slug": "sports-mythic-gold-roster-2",
    "name": "Mythic Gold Roster",
    "icon": "?",
    "animationType": "wave",
    "coinCost": 2267,
    "tier": "Mythic",
    "category": "Sports",
    "description": "A mythic sports token that celebrates with a roaring victory pulse.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "music-common-rhythm-flame-1",
    "gift_slug": "music-common-rhythm-flame-1",
    "name": "Common Rhythm Flame",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 168,
    "tier": "Common",
    "category": "Music",
    "description": "A common music token that drops a rhythm storm of glowing chords.",
    "popularityScore": 68,
    "imageUrl": "https://images.unsplash.com/photo-1464375117522-1311d6a5b9d5?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "music-common-bass-pulse-2",
    "gift_slug": "music-common-bass-pulse-2",
    "name": "Common Bass Pulse",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 193,
    "tier": "Common",
    "category": "Music",
    "description": "A common music token that spins a bassline wrapped in gold.",
    "popularityScore": 71,
    "imageUrl": "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "music-rare-bass-pulse-1",
    "gift_slug": "music-rare-bass-pulse-1",
    "name": "Rare Bass Pulse",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 328,
    "tier": "Rare",
    "category": "Music",
    "description": "A rare music token that hangs a chorus from the neon rafters.",
    "popularityScore": 79,
    "imageUrl": "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "music-rare-neon-chorus-2",
    "gift_slug": "music-rare-neon-chorus-2",
    "name": "Rare Neon Chorus",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 353,
    "tier": "Rare",
    "category": "Music",
    "description": "A rare music token that lets echoes bloom in gilded harmony.",
    "popularityScore": 82,
    "imageUrl": "https://images.unsplash.com/photo-1507878866276-a947ef722fee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "music-epic-neon-chorus-1",
    "gift_slug": "music-epic-neon-chorus-1",
    "name": "Epic Neon Chorus",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 568,
    "tier": "Epic",
    "category": "Music",
    "description": "A epic music token that opens the stream with a vibrant beat.",
    "popularityScore": 88,
    "imageUrl": "https://images.unsplash.com/photo-1507878866276-a947ef722fee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "music-epic-echo-halo-2",
    "gift_slug": "music-epic-echo-halo-2",
    "name": "Epic Echo Halo",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 593,
    "tier": "Epic",
    "category": "Music",
    "description": "A epic music token that drops a rhythm storm of glowing chords.",
    "popularityScore": 91,
    "imageUrl": "https://images.unsplash.com/photo-1464375117522-1311d6a5b9d5?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "music-legendary-echo-halo-1",
    "gift_slug": "music-legendary-echo-halo-1",
    "name": "Legendary Echo Halo",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1148,
    "tier": "Legendary",
    "category": "Music",
    "description": "A legendary music token that spins a bassline wrapped in gold.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1464375117522-1311d6a5b9d5?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "music-legendary-rhythm-flame-2",
    "gift_slug": "music-legendary-rhythm-flame-2",
    "name": "Legendary Rhythm Flame",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1173,
    "tier": "Legendary",
    "category": "Music",
    "description": "A legendary music token that hangs a chorus from the neon rafters.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "music-mythic-rhythm-flame-1",
    "gift_slug": "music-mythic-rhythm-flame-1",
    "name": "Mythic Rhythm Flame",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2248,
    "tier": "Mythic",
    "category": "Music",
    "description": "A mythic music token that lets echoes bloom in gilded harmony.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "music-mythic-bass-pulse-2",
    "gift_slug": "music-mythic-bass-pulse-2",
    "name": "Mythic Bass Pulse",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2273,
    "tier": "Mythic",
    "category": "Music",
    "description": "A mythic music token that opens the stream with a vibrant beat.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1507878866276-a947ef722fee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "fantasy-common-celestial-bloom-1",
    "gift_slug": "fantasy-common-celestial-bloom-1",
    "name": "Common Celestial Bloom",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 189,
    "tier": "Common",
    "category": "Fantasy",
    "description": "A common fantasy token that veils the feed in mythic shimmer.",
    "popularityScore": 70,
    "imageUrl": "https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "fantasy-common-elder-star-2",
    "gift_slug": "fantasy-common-elder-star-2",
    "name": "Common Elder Star",
    "icon": "???",
    "animationType": "glow",
    "coinCost": 214,
    "tier": "Common",
    "category": "Fantasy",
    "description": "A common fantasy token that opens a portal of cosmic twinkle.",
    "popularityScore": 73,
    "imageUrl": "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "fantasy-rare-elder-star-1",
    "gift_slug": "fantasy-rare-elder-star-1",
    "name": "Rare Elder Star",
    "icon": "???",
    "animationType": "spark",
    "coinCost": 349,
    "tier": "Rare",
    "category": "Fantasy",
    "description": "A rare fantasy token that weaves a dream cloak across the stage.",
    "popularityScore": 81,
    "imageUrl": "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "fantasy-rare-dream-ward-2",
    "gift_slug": "fantasy-rare-dream-ward-2",
    "name": "Rare Dream Ward",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 374,
    "tier": "Rare",
    "category": "Fantasy",
    "description": "A rare fantasy token that summons guardian lights from far realms.",
    "popularityScore": 84,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "fantasy-epic-dream-ward-1",
    "gift_slug": "fantasy-epic-dream-ward-1",
    "name": "Epic Dream Ward",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 589,
    "tier": "Epic",
    "category": "Fantasy",
    "description": "A epic fantasy token that lets loose a starry blaze through chat.",
    "popularityScore": 90,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "fantasy-epic-wardens-call-2",
    "gift_slug": "fantasy-epic-wardens-call-2",
    "name": "Epic Wardens Call",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 614,
    "tier": "Epic",
    "category": "Fantasy",
    "description": "A epic fantasy token that veils the feed in mythic shimmer.",
    "popularityScore": 93,
    "imageUrl": "https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "fantasy-legendary-wardens-call-1",
    "gift_slug": "fantasy-legendary-wardens-call-1",
    "name": "Legendary Wardens Call",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1169,
    "tier": "Legendary",
    "category": "Fantasy",
    "description": "A legendary fantasy token that opens a portal of cosmic twinkle.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "fantasy-legendary-celestial-bloom-2",
    "gift_slug": "fantasy-legendary-celestial-bloom-2",
    "name": "Legendary Celestial Bloom",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1194,
    "tier": "Legendary",
    "category": "Fantasy",
    "description": "A legendary fantasy token that weaves a dream cloak across the stage.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "fantasy-mythic-celestial-bloom-1",
    "gift_slug": "fantasy-mythic-celestial-bloom-1",
    "name": "Mythic Celestial Bloom",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2269,
    "tier": "Mythic",
    "category": "Fantasy",
    "description": "A mythic fantasy token that summons guardian lights from far realms.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "fantasy-mythic-elder-star-2",
    "gift_slug": "fantasy-mythic-elder-star-2",
    "name": "Mythic Elder Star",
    "icon": "???",
    "animationType": "wave",
    "coinCost": 2294,
    "tier": "Mythic",
    "category": "Fantasy",
    "description": "A mythic fantasy token that lets loose a starry blaze through chat.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "troll-city-special-common-denizen-drift-1",
    "gift_slug": "troll-city-special-common-denizen-drift-1",
    "name": "Common Denizen Drift",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 205,
    "tier": "Common",
    "category": "Troll City Special",
    "description": "A common troll city special token that powers the skyline with chaos gold.",
    "popularityScore": 72,
    "imageUrl": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "troll-city-special-common-courtroom-flame-2",
    "gift_slug": "troll-city-special-common-courtroom-flame-2",
    "name": "Common Courtroom Flame",
    "icon": "???",
    "animationType": "glow",
    "coinCost": 230,
    "tier": "Common",
    "category": "Troll City Special",
    "description": "A common troll city special token that drops civic sparks across the court.",
    "popularityScore": 75,
    "imageUrl": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "troll-city-special-rare-courtroom-flame-1",
    "gift_slug": "troll-city-special-rare-courtroom-flame-1",
    "name": "Rare Courtroom Flame",
    "icon": "???",
    "animationType": "spark",
    "coinCost": 365,
    "tier": "Rare",
    "category": "Troll City Special",
    "description": "A rare troll city special token that crowns the room with neon authority.",
    "popularityScore": 83,
    "imageUrl": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "troll-city-special-rare-troll-crown-2",
    "gift_slug": "troll-city-special-rare-troll-crown-2",
    "name": "Rare Troll Crown",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 390,
    "tier": "Rare",
    "category": "Troll City Special",
    "description": "A rare troll city special token that flares a troll anthem through chat.",
    "popularityScore": 86,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "troll-city-special-epic-troll-crown-1",
    "gift_slug": "troll-city-special-epic-troll-crown-1",
    "name": "Epic Troll Crown",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 605,
    "tier": "Epic",
    "category": "Troll City Special",
    "description": "A epic troll city special token that rises like a skyline beacon of mischief.",
    "popularityScore": 92,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "troll-city-special-epic-city-pulse-2",
    "gift_slug": "troll-city-special-epic-city-pulse-2",
    "name": "Epic City Pulse",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 630,
    "tier": "Epic",
    "category": "Troll City Special",
    "description": "A epic troll city special token that powers the skyline with chaos gold.",
    "popularityScore": 95,
    "imageUrl": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "troll-city-special-legendary-city-pulse-1",
    "gift_slug": "troll-city-special-legendary-city-pulse-1",
    "name": "Legendary City Pulse",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1185,
    "tier": "Legendary",
    "category": "Troll City Special",
    "description": "A legendary troll city special token that drops civic sparks across the court.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "troll-city-special-legendary-denizen-drift-2",
    "gift_slug": "troll-city-special-legendary-denizen-drift-2",
    "name": "Legendary Denizen Drift",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1210,
    "tier": "Legendary",
    "category": "Troll City Special",
    "description": "A legendary troll city special token that crowns the room with neon authority.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "troll-city-special-mythic-denizen-drift-1",
    "gift_slug": "troll-city-special-mythic-denizen-drift-1",
    "name": "Mythic Denizen Drift",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2285,
    "tier": "Mythic",
    "category": "Troll City Special",
    "description": "A mythic troll city special token that flares a troll anthem through chat.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "troll-city-special-mythic-courtroom-flame-2",
    "gift_slug": "troll-city-special-mythic-courtroom-flame-2",
    "name": "Mythic Courtroom Flame",
    "icon": "???",
    "animationType": "wave",
    "coinCost": 2310,
    "tier": "Mythic",
    "category": "Troll City Special",
    "description": "A mythic troll city special token that rises like a skyline beacon of mischief.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "ultra-permanent-chat",
    "gift_slug": "ultra-permanent-chat",
    "name": "Ultra Permanent Chat",
    "icon": "🌀",
    "animationType": "wave",
    "coinCost": 2499,
    "tier": "Mythic",
    "category": "Troll City Special",
    "description": "A mythic Trollmonds-exclusive that etches a glowing chat ribbon into every stream and whispers legacy energy.",
    "popularityScore": 100,
    "imageUrl": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "holidays-common-frosted-ember-1",
    "gift_slug": "holidays-common-frosted-ember-1",
    "name": "Common Frosted Ember",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 186,
    "tier": "Common",
    "category": "Holidays",
    "description": "A common holidays token that brings warmth like a gilded hearth.",
    "popularityScore": 74,
    "imageUrl": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "holidays-common-yuletide-gold-2",
    "gift_slug": "holidays-common-yuletide-gold-2",
    "name": "Common Yuletide Gold",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 211,
    "tier": "Common",
    "category": "Holidays",
    "description": "A common holidays token that sends frosted whispers across the scene.",
    "popularityScore": 77,
    "imageUrl": "https://images.unsplash.com/photo-1422242107440-1c9a14b44476?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "holidays-rare-yuletide-gold-1",
    "gift_slug": "holidays-rare-yuletide-gold-1",
    "name": "Rare Yuletide Gold",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 346,
    "tier": "Rare",
    "category": "Holidays",
    "description": "A rare holidays token that strings a carol of neon bells.",
    "popularityScore": 85,
    "imageUrl": "https://images.unsplash.com/photo-1422242107440-1c9a14b44476?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "holidays-rare-starfall-carol-2",
    "gift_slug": "holidays-rare-starfall-carol-2",
    "name": "Rare Starfall Carol",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 371,
    "tier": "Rare",
    "category": "Holidays",
    "description": "A rare holidays token that drops a sparkling gift of light.",
    "popularityScore": 88,
    "imageUrl": "https://images.unsplash.com/photo-1511458114786-6ab6d7e9f02c?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "holidays-epic-starfall-carol-1",
    "gift_slug": "holidays-epic-starfall-carol-1",
    "name": "Epic Starfall Carol",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 586,
    "tier": "Epic",
    "category": "Holidays",
    "description": "A epic holidays token that wraps everyone in glittering cheer.",
    "popularityScore": 94,
    "imageUrl": "https://images.unsplash.com/photo-1511458114786-6ab6d7e9f02c?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "holidays-epic-hearth-spark-2",
    "gift_slug": "holidays-epic-hearth-spark-2",
    "name": "Epic Hearth Spark",
    "icon": "???",
    "animationType": "burst",
    "coinCost": 611,
    "tier": "Epic",
    "category": "Holidays",
    "description": "A epic holidays token that brings warmth like a gilded hearth.",
    "popularityScore": 97,
    "imageUrl": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "holidays-legendary-hearth-spark-1",
    "gift_slug": "holidays-legendary-hearth-spark-1",
    "name": "Legendary Hearth Spark",
    "icon": "???",
    "animationType": "pulse",
    "coinCost": 1166,
    "tier": "Legendary",
    "category": "Holidays",
    "description": "A legendary holidays token that sends frosted whispers across the scene.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "holidays-legendary-frosted-ember-2",
    "gift_slug": "holidays-legendary-frosted-ember-2",
    "name": "Legendary Frosted Ember",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1191,
    "tier": "Legendary",
    "category": "Holidays",
    "description": "A legendary holidays token that strings a carol of neon bells.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1422242107440-1c9a14b44476?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "holidays-mythic-frosted-ember-1",
    "gift_slug": "holidays-mythic-frosted-ember-1",
    "name": "Mythic Frosted Ember",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2266,
    "tier": "Mythic",
    "category": "Holidays",
    "description": "A mythic holidays token that drops a sparkling gift of light.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1422242107440-1c9a14b44476?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "holidays-mythic-yuletide-gold-2",
    "gift_slug": "holidays-mythic-yuletide-gold-2",
    "name": "Mythic Yuletide Gold",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2291,
    "tier": "Mythic",
    "category": "Holidays",
    "description": "A mythic holidays token that wraps everyone in glittering cheer.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1511458114786-6ab6d7e9f02c?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "vip-common-executive-glide-1",
    "gift_slug": "vip-common-executive-glide-1",
    "name": "Common Executive Glide",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 227,
    "tier": "Common",
    "category": "VIP",
    "description": "A common vip token that grants a rare glow reserved for legends.",
    "popularityScore": 76,
    "imageUrl": "https://images.unsplash.com/photo-1493666438817-866a91353ca9?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "vip-common-velvet-ledger-2",
    "gift_slug": "vip-common-velvet-ledger-2",
    "name": "Common Velvet Ledger",
    "icon": "??",
    "animationType": "glow",
    "coinCost": 252,
    "tier": "Common",
    "category": "VIP",
    "description": "A common vip token that slides a velvet flair onto the stream.",
    "popularityScore": 79,
    "imageUrl": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "vip-rare-velvet-ledger-1",
    "gift_slug": "vip-rare-velvet-ledger-1",
    "name": "Rare Velvet Ledger",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 387,
    "tier": "Rare",
    "category": "VIP",
    "description": "A rare vip token that floats a monarch token over the crowd.",
    "popularityScore": 87,
    "imageUrl": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "vip-rare-monarch-token-2",
    "gift_slug": "vip-rare-monarch-token-2",
    "name": "Rare Monarch Token",
    "icon": "??",
    "animationType": "spark",
    "coinCost": 412,
    "tier": "Rare",
    "category": "VIP",
    "description": "A rare vip token that opens a celestial pass of gold.",
    "popularityScore": 90,
    "imageUrl": "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "vip-epic-monarch-token-1",
    "gift_slug": "vip-epic-monarch-token-1",
    "name": "Epic Monarch Token",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 627,
    "tier": "Epic",
    "category": "VIP",
    "description": "A epic vip token that glides exclusive sparkles through chat.",
    "popularityScore": 96,
    "imageUrl": "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "vip-epic-celestial-pass-2",
    "gift_slug": "vip-epic-celestial-pass-2",
    "name": "Epic Celestial Pass",
    "icon": "??",
    "animationType": "burst",
    "coinCost": 652,
    "tier": "Epic",
    "category": "VIP",
    "description": "A epic vip token that grants a rare glow reserved for legends.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1493666438817-866a91353ca9?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "vip-legendary-celestial-pass-1",
    "gift_slug": "vip-legendary-celestial-pass-1",
    "name": "Legendary Celestial Pass",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1207,
    "tier": "Legendary",
    "category": "VIP",
    "description": "A legendary vip token that slides a velvet flair onto the stream.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1493666438817-866a91353ca9?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "vip-legendary-executive-glide-2",
    "gift_slug": "vip-legendary-executive-glide-2",
    "name": "Legendary Executive Glide",
    "icon": "??",
    "animationType": "pulse",
    "coinCost": 1232,
    "tier": "Legendary",
    "category": "VIP",
    "description": "A legendary vip token that floats a monarch token over the crowd.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "vip-mythic-executive-glide-1",
    "gift_slug": "vip-mythic-executive-glide-1",
    "name": "Mythic Executive Glide",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2307,
    "tier": "Mythic",
    "category": "VIP",
    "description": "A mythic vip token that opens a celestial pass of gold.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=70"
  },
  {
    "id": "vip-mythic-velvet-ledger-2",
    "gift_slug": "vip-mythic-velvet-ledger-2",
    "name": "Mythic Velvet Ledger",
    "icon": "??",
    "animationType": "wave",
    "coinCost": 2332,
    "tier": "Mythic",
    "category": "VIP",
    "description": "A mythic vip token that glides exclusive sparkles through chat.",
    "popularityScore": 99,
    "imageUrl": "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=600&q=70"
  }
];

export const giftCategories = [
  "Love",
  "Funny",
  "Luxury",
  "Animals",
  "Food",
  "Magic",
  "Party",
  "Sports",
  "Music",
  "Fantasy",
  "Troll City Special",
  "Holidays",
  "VIP"
];
export const giftTiers = [
  "Common",
  "Rare",
  "Epic",
  "Legendary",
  "Mythic"
];
export const tierPriority = {
  "Common": 1,
  "Rare": 2,
  "Epic": 3,
  "Legendary": 4,
  "Mythic": 5
};

export default giftCatalog;
