
CREATE TABLE public.troll_officer_alerts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now() not null,
    target_user_id uuid not null,
    reporting_broadofficer_id uuid not null,
    stream_id uuid not null,
    reason text,
    acknowledged_by uuid,
    acknowledged_at timestamp with time zone,
    constraint target_user_id_fkey foreign key (target_user_id) references user_profiles (id) on delete cascade,
    constraint reporting_broadofficer_id_fkey foreign key (reporting_broadofficer_id) references user_profiles (id) on delete cascade,
    constraint acknowledged_by_fkey foreign key (acknowledged_by) references user_profiles (id) on delete set null
);

CREATE OR REPLACE FUNCTION public.alert_troll_officers(p_target_user_id uuid, p_stream_id uuid, p_reason text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_broadofficer_id uuid;
  v_broadcaster_id uuid;
BEGIN
  v_broadofficer_id := auth.uid();

  -- Get the broadcaster of the stream
  SELECT broadcaster_id INTO v_broadcaster_id
  FROM streams
  WHERE id = p_stream_id;

  -- Check if the caller is a broadofficer for this stream
  IF NOT EXISTS (
    SELECT 1
    FROM public.broadcast_officers
    WHERE officer_id = v_broadofficer_id AND broadcaster_id = v_broadcaster_id
  ) THEN
    RAISE EXCEPTION 'Only assigned broadofficers can alert Troll Officers.';
  END IF;

  -- Insert the alert
  INSERT INTO public.troll_officer_alerts (target_user_id, reporting_broadofficer_id, stream_id, reason)
  VALUES (p_target_user_id, v_broadofficer_id, p_stream_id, p_reason);
END;
$$;

ALTER TABLE public.troll_officer_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Troll Officers can see all alerts" ON public.troll_officer_alerts
  FOR SELECT
  USING ((SELECT role FROM public.user_profiles WHERE id = auth.uid()) IN ('troll_officer', 'lead_troll_officer', 'admin'));

CREATE POLICY "Broadofficers can see their own alerts" ON public.troll_officer_alerts
  FOR SELECT
  USING (reporting_broadofficer_id = auth.uid());
