-- Create stream_likes table
CREATE TABLE IF NOT EXISTS public.stream_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id UUID REFERENCES public.streams(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (stream_id, user_id)
);

-- Create like_stream function
CREATE OR REPLACE FUNCTION public.like_stream(p_stream_id UUID)
RETURNS JSONB AS $$
DECLARE
    v_user_id UUID;
BEGIN
    v_user_id := auth.uid();

    -- Insert the like
    INSERT INTO public.stream_likes (stream_id, user_id)
    VALUES (p_stream_id, v_user_id)
    ON CONFLICT (stream_id, user_id) DO NOTHING;

    -- Broadcast the like event
    PERFORM supabase_functions.http_request(
        CONCAT(current_setting('supabase.functions.url'), '/send-message'),
        'POST',
        '{
            "type": "broadcast",
            "event": "like_sent",
            "channel": "stream:' || p_stream_id || '",
            "payload": {
                "user_id": "' || v_user_id || '"
            }
        }',
        'application/json',
        CONCAT('Bearer ', current_setting('supabase.auth.service_role_key'))
    );

    RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;