-- Create stream_viewers table
CREATE TABLE IF NOT EXISTS public.stream_viewers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id UUID REFERENCES public.streams(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (stream_id, user_id)
);

-- Create stream_bans table
CREATE TABLE IF NOT EXISTS public.stream_bans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id UUID REFERENCES public.streams(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    banned_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    reason TEXT,
    banned_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ
);

-- Create ban_user_from_stream function
CREATE OR REPLACE FUNCTION public.ban_user_from_stream(p_stream_id UUID, p_user_id UUID, p_reason TEXT)
RETURNS JSONB AS $$
DECLARE
    v_banned_by_user_id UUID;
BEGIN
    v_banned_by_user_id := auth.uid();

    INSERT INTO public.stream_bans (stream_id, user_id, banned_by, reason)
    VALUES (p_stream_id, p_user_id, v_banned_by_user_id, p_reason);

    RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;